print("Enter the present value of the account un dollars")
value=input()
print("Enter the annual percentage rate")
rate=input()
print("The information for our account is ")
print("Present value :$"+str(str(value)))
print("Intersest Rate: "+str(rate))
newValue=float(value)*((1+((int(rate)/100)/12))**12)
print("After 12 months, the value of your account will be $"+str(format(newValue,',.2f')))
